#----------------------------------------------------------------------------------------------
FROM raffapen/redis-arm64-bionic-qemu:latest AS builder

RUN [ "cross-build-start" ]

ADD . /build
WORKDIR /build

# COPY --from=redis /usr/local/bin/* /usr/local/bin/

RUN ./deps/readies/bin/getpy2
RUN python system-setup.py
RUN make get_deps
RUN make all SHOW=1 PYTHON_ENCODING=ucs4

RUN [ "cross-build-end" ]

#----------------------------------------------------------------------------------------------
FROM raffapen/redis-arm64-bionic-qemu:latest

RUN [ "cross-build-start" ]

# COPY --from=redis /usr/local/bin/* /usr/local/bin/

ENV REDIS_MODULES /opt/redislabs/lib/modules

RUN mkdir -p $REDIS_MODULES/

COPY --from=builder /build/redisgears.so $REDIS_MODULES/
COPY --from=builder /build/artifacts/release/redisgears-dependencies.*.tgz /tmp/

RUN tar xzf /tmp/redisgears-dependencies.*.tgz -C /

CMD ["--loadmodule", "/opt/redislabs/lib/modules/redisgears.so", "PythonHomeDir", "/opt/redislabs/lib/modules/python3"]

RUN [ "cross-build-end" ]
