# BUILD redisfab/redisgears-${ARCH}-${OSNICK}:M.m.b

ARG OSNICK=bionic
ARG ARCH=arm64

#----------------------------------------------------------------------------------------------
FROM redisfab/redis-${ARCH}-${OSNICK}-xbuild:5.0.5 AS builder

RUN [ "cross-build-start" ]

ADD . /build
WORKDIR /build

RUN ./deps/readies/bin/getpy2
RUN python system-setup.py
RUN make get_deps
RUN make all SHOW=1

RUN [ "cross-build-end" ]

#----------------------------------------------------------------------------------------------
FROM redisfab/redis-${ARCH}-${OSNICK}-xbuild:5.0.5

RUN [ "cross-build-start" ]

ENV REDIS_MODULES /opt/redislabs/lib/modules

RUN mkdir -p $REDIS_MODULES/

COPY --from=builder /build/redisgears.so $REDIS_MODULES/
COPY --from=builder /build/artifacts/release/redisgears-dependencies.*.tgz /tmp/

RUN tar xzf /tmp/redisgears-dependencies.*.tgz -C /

CMD ["--loadmodule", "/opt/redislabs/lib/modules/redisgears.so", "PythonHomeDir", "/opt/redislabs/lib/modules/python3"]

RUN [ "cross-build-end" ]
