#!/bin/bash

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"

export PATH=$PATH:/opt/oracle/instantclient_19_5

cd $HERE/..

cat create-user.sql | sqlplus system/oracle@//oracle/xe
cat create-db.sql | sqlplus test/passwd@//oracle/xe
