#!/bin/bash

TIMEOUT=${TIMEOUT:-120}

# this is required so sqlplus does not hang is oracle
./wait-for-it.sh oracle:1521 -t 2
if [[ $? != 0 ]]; then
	echo "Oracle is not present. Aborting."
	exit 1
fi

for ((i = 0; i < $TIMEOUT; i++)); do
	# this still can hang, so we really need to start it as a job and kill it
	# if it does not come back within a second
	echo "select * from dual" | sqlplus -S -L system/oracle@//oracle:1521/xe > /dev/null 2>&1
	[[ $? == 0 ]] && exit 0
	sleep 1
done
echo "Oracle is not ready. Aborting."
exit 1
