#!/bin/bash

# run this as root

[[ $VERBOSE == 1 ]] && set -x
[[ $IGNERR == 1 ]] || set -e

if [ ! -z $(command -v apt-get) ]; then
	apt-get -qq update
	apt-get install -y cassandra
	
elif [ ! -z $(command -v yum) ]; then
	yum install -y cassandra
else
	echo "%make love"
	echo "Make:  Don't know how to make love.  Stop."
	exit 1
fi

exit 0
