#!/bin/bash

[[ $VERBOSE == 1 ]] && set -x
[[ $IGNERR == 1 ]] || set -e

DSE_IMAGE=datastax/dse-server:5.1.17

DSE=dse1
rm -f /tmp/dse1.cid
docker stop $DSE > /dev/null 2>&1 || true
docker rm $DSE > /dev/null 2>&1 || true
sleep 3

docker run --cidfile /tmp/dse1.cid --rm -e DS_LICENSE=accept --name $DSE -v /opt/recipe:/opt/recipe -p 9042:9042 -d $DSE_IMAGE
docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' $DSE > /tmp/dse1.ip
echo "Cassandra IP: `cat /tmp/dse1.ip`"

exit 0
