#!/bin/bash

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"

MYSQL=${MYSQL:-mysql}

cd $HERE/..

cat create-user.sql | mysql -h $MYSQL -ppasswd
cat create-db.sql | mysql -h $MYSQL -utest -ppasswd
