#!/bin/bash

set -e

MYSQL_IMAGE=mysql:8

MYSQL=mysql
docker rm -f $MYSQL || true
rm -f /tmp/mysql.cid
docker run --cidfile /tmp/mysql.cid --rm -d --name $MYSQL -e MYSQL_ROOT_PASSWORD=passwd -p 3306:3306 $MYSQL_IMAGE
docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' $MYSQL > /tmp/mysql.ip
cat /tmp/mysql.ip

exit 0
