#!/bin/bash

if [[ $STAGE == precluster ]]; then
	oracle=`cat /opt/view/rlec/ORACLE.ip`
	printf "\n$oracle oracle\n" >> /etc/hosts

	cd /opt
	ln -s /opt/view/RedisGears/recipes/write_behind recipe

	/opt/recipe/oracle/install-oracle-client
	/opt/recipe/oracle/install-oracle-python-client

elif [[ $STAGE == postcluster ]]; then
	ID=1 /opt/recipe/oracle/rlec-docker/start-gear
fi

## RECIPE=cat /opt/recipe/oracle/create-user.sql | sqlplus system/oracle@$oracle
## cat /opt/recipe/oracle/create-db.sql | sqlplus test/passwd@$oracle
