
CREATE DATABASE test;
USE DATABASE test;

CREATE TABLE person1 (
  id VARCHAR(100) NOT NULL,
  first VARCHAR(100) NOT NULL,
  last VARCHAR(100) NOT NULL,
  age VARCHAR(100) NOT NULL,
  PRIMARY KEY (id));

CREATE TABLE car (
  license VARCHAR(100) NOT NULL,
  color VARCHAR(100) NOT NULL,
  PRIMARY KEY (license));
