#!/bin/bash

# run this as root

[[ $VERBOSE == 1 ]] && set -x
[[ $IGNERR == 1 ]] || set -e

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"
cd $HERE

if [ ! -z $(command -v apt-get) ]; then
	apt-get -qq update
	apt-get install -y ca-certificates wget curl
elif [ ! -z $(command -v yum) ]; then
	yum install -y ca-certificates curl wget
else
	echo "%make love"
	echo "Make:  Don't know how to make love.  Stop."
	exit 1
fi

rm -f /tmp/snowsql.sh
curl -s -o /tmp/snowsql.sh https://sfc-repo.snowflakecomputing.com/snowsql/bootstrap/1.2/linux_x86_64/snowsql-1.2.2-linux_x86_64.bash
printf "/usr/local/bin\n\n" | bash /tmp/snowsql.sh

exit 0
