#!/bin/bash

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"

source /etc/opt/redislabs/redislabs_env_config.sh
export PYTHONPATH=${cnmlibdir}:${cnmlibdir}/python:${PYTHONPATH}
exec ${pythonexec} ${pythonflags} $HERE/redis-conn.py "${@}"
