#!/bin/bash

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"

ORACLE=${ORACLE:-oracle}

export PATH=/opt/oracle/instantclient_19_5:$PATH

cd $HERE/..

cat create-user.sql | sqlplus system/oracle@//$ORACLE/xe
cat create-db.sql | sqlplus test/passwd@//$ORACLE/xe
