#!/bin/bash

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)" 

CONN=`$HERE/redis-conn`
if [[ $? != 0 ]]; then
	echo "start-gear: not started."
	exit 1
fi

cd $HERE/../..
/opt/redislabs/bin/python ./tests/test_write_behind.py $CONN
