/*
 * version.h
 *
 *  Created on: Sep 17, 2018
 *      Author: meir
 */

#ifndef SRC_VERSION_H_
#define SRC_VERSION_H_

#define REDISGEARSJVM_VERSION_MAJOR 99
#define REDISGEARSJVM_VERSION_MINOR 99
#define REDISGEARSJVM_VERSION_PATCH 99

#define STR1(a) #a
#define STR(e) STR1(e)

#define REDISGEARSJVM_PLUGIN_VERSION \
  (REDISGEARSJVM_VERSION_MAJOR * 10000 + REDISGEARSJVM_VERSION_MINOR * 100 + REDISGEARSJVM_VERSION_PATCH)

#define REDISGEARSJVM_VERSION_STR STR(REDISGEARS_VERSION_MAJOR) "." STR(REDISGEARS_VERSION_MINOR) "." STR(REDISGEARS_VERSION_PATCH)

#define REDISGEARSJVM_PLUGIN_NAME "GearsJVMPlugin"

#endif /* SRC_VERSION_H_ */
