#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
. $DIR/pyenv
redis-server --loadmodule ./redisgears.so
# gdb `which redis-server` --args --loadmodule ./redisgears.so
