{% include "base.incl" %}

RUN mkdir -p /build/target/release
RUN touch /build/target/release/foo
RUN touch /build/target/release/bar
RUN touch /build/target/release/blee
RUN echo "sm" > /build/target/release/output
