{% include "base.incl" %}

RUN ln -fs /usr/share/zoneinfo/America/New_York /etc/localtime
RUN apt-get update -qq

{% if OS_FAMILY == "ubuntu" %}
{% if OS_VERSION == "22.04" or OS_VERSION == "20.04" %}
RUN DEBIAN_FRONTEND=noninteractive apt-get install -qqy git build-essential autoconf libtool curl libssl-dev pkg-config clang wget python3 python3-pip lsb-release unzip zip
{% elif OS_VERSION == "18.04" %}
RUN apt -yqq install software-properties-common
RUN add-apt-repository ppa:ubuntu-toolchain-r/test
RUN add-apt-repository ppa:git-core/ppa
RUN apt-get update -qq
RUN DEBIAN_FRONTEND=noninteractive apt -yqq install git gcc-9 g++-9 curl wget python3.8 python3.8-dev dialog subversion chrpath libssl-dev python3-dev clang autoconf automake libtool pkg-config unzip lsb-release zip
RUN update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-9 9
RUN update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-9 9
RUN update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.8 10
RUN curl -sS https://bootstrap.pypa.io/get-pip.py | python3
{% endif %}
{% elif OS_FAMILY == "debian" %}
RUN DEBIAN_FRONTEND=noninteractive apt-get install -qqy git build-essential autoconf libtool curl libssl-dev pkg-config clang wget python3 python3-pip lsb-release unzip zip
{% endif %}

{% include "pip.incl" %}

{% include "build_and_test.incl" %}

{% include "copyfrom.incl" %}
