name: Branch Merge

on:
    push:
        paths-ignore:
            - '.circleci/**'
            - 'docs/**'
            - '*.md'
        branches:
            - main
            - master
            - '[0-9]+.[0-9]+.[0-9]+'
            - '[0-9]+.[0-9]+'
        tags:
            - 'v[0-9]+.[0-9]+.[0-9]+-rc[0-9]+'
            - 'v[0-9]+.[0-9]+.[0-9]+-m[0-9]+'

jobs:

    jammy-x86:
        uses: ./.github/workflows/REUSABLE_DOCKER_BUILDER.yml
        with:
            os_version: 22.04
            os_family: ubuntu
            dockerfile: dockerbuilds/dockerfile.debian.tmpl
            publish: true
        secrets:
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY }}

    focal-x86:
        uses: ./.github/workflows/REUSABLE_DOCKER_BUILDER.yml
        with:
            os_version: 20.04
            os_family: ubuntu
            dockerfile: dockerbuilds/dockerfile.debian.tmpl
            publish: true
        secrets:
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY }}

    bionic-x86:
        uses: ./.github/workflows/REUSABLE_DOCKER_BUILDER.yml
        with:
            os_version: 18.04
            os_family: ubuntu
            dockerfile: dockerbuilds/dockerfile.debian.tmpl
            publish: true
        secrets:
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY }}

    bullseye-x86:
        uses: ./.github/workflows/REUSABLE_DOCKER_BUILDER.yml
        with:
            os_version: bullseye
            os_family: debian
            dockerfile: dockerbuilds/dockerfile.debian.tmpl
            publish: true
        secrets:
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY }}

    amazonlinux2-x86:
        uses: ./.github/workflows/REUSABLE_DOCKER_BUILDER.yml
        with:
            os_version: 2
            os_family: amazonlinux
            dockerfile: dockerbuilds/dockerfile.rhel.tmpl
            publish: true
        secrets:
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY }}

    rhel7-x86:
        uses: ./.github/workflows/REUSABLE_DOCKER_BUILDER.yml
        with:
            os_version: 7
            os_family: centos
            dockerfile: dockerbuilds/dockerfile.rhel.tmpl
            publish: true
        secrets:
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY }}

    rhel8-x86:
        uses: ./.github/workflows/REUSABLE_DOCKER_BUILDER.yml
        with:
            os_version: 8
            os_family: rockylinux
            dockerfile: dockerbuilds/dockerfile.rhel.tmpl
            publish: true
        secrets:
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY }}
