name: CI

on:
  push:
    branches:
      - '**'
    tags:
      - '**'
  pull_request:

jobs:
  build-with-redis:
    name: ${{ matrix.osnick }}, redis ${{ matrix.redis_version }}
    if: ${{ !endsWith(github.ref_name, 'docs') && !endsWith(github.ref_name, 'noci') }}
    runs-on: ubuntu-latest
    timeout-minutes: 60
    container:
      image: ${{ matrix.container }}
      options: --user root
    strategy:
      fail-fast: false
      matrix:
        osnick: ['rocky8', 'rocky9', 'ubuntu20.04', 'ubuntu22.04']
        include:
          - osnick: rocky8
            container: rockylinux:8
            pre_req_install_cmd: dnf install -y git curl ca-certificates make tar gzip
          - osnick: rocky9
            container: rockylinux:9
            pre_req_install_cmd: dnf install -y git curl ca-certificates make tar gzip
          - osnick: ubuntu20.04
            container: ubuntu:focal
            pre_req_install_cmd: apt-get update && apt-get install -y software-properties-common && add-apt-repository ppa:git-core/ppa && apt-get update && apt-get install -y git curl ca-certificates make tar gzip
          - osnick: ubuntu22.04
            container: ubuntu:jammy
            pre_req_install_cmd: apt-get update && apt-get install -y software-properties-common && add-apt-repository ppa:git-core/ppa && apt-get update && apt-get install -y git curl ca-certificates make tar gzip
        redis_version: ['6.4', '7.2', '7.4']
    steps:
      - name: Install pre-requisites
        shell: bash
        run: |
          ${{ matrix.pre_req_install_cmd }}
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup automation
        shell: bash
        run: |
          git submodule update --init deps/readies
          ./deps/readies/bin/getpy3

      - name: System setup
        shell: bash
        run: |
          ./system-setup.py
          ./plugins/jvmplugin/system-setup.py
          echo "python3: $(command -v python3)"
          python3 --version
          python3 -m pip list

      - name: Install Redis ${{ matrix.redis_version }}
        shell: bash
        run: |
          export HOMEBREW_NO_AUTO_UPDATE=1
          ./deps/readies/bin/getredis -v ${{ matrix.redis_version }} --force
          redis-server --version

      - name: Build
        shell: bash
        run: make all SHOW=1

      - name: Gears Tests
        shell: bash
        run: make test

      - name: Upload pytest logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: pytest-logs-${{ matrix.redis_version }}
          path: pytest/logs


