name: Event Tag

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  build-all-platforms-and-publish-release:
    uses: ./.github/workflows/flow-gears.yaml

    with:
      os: ""
      publish_snapshot: false
      publish_release: true
    secrets: inherit

