name: Master Build and Test

on:

  workflow_dispatch:

  schedule:
    - cron: "0 5 * * *"

env:
  CARGO_TERM_COLOR: always

jobs:
  build-and-test-focal:
    uses: ./.github/workflows/UBUNTU_FOCAL_REUSABLE.yml
    with:
      v8_version: main
      v8_update_headers: yes
  build-and-test-bionic:
    uses: ./.github/workflows/UBUNTU_BIONIC_REUSABLE.yml
    with:
      v8_version: main
      v8_update_headers: yes
  build-and-test-centos_8:
    uses: ./.github/workflows/CENTOS_8_REUSABLE.yml
    with:
      v8_version: main
      v8_update_headers: yes
  build-and-test-centos_7:
    uses: ./.github/workflows/CENTOS_7_REUSABLE.yml
    with:
      v8_version: main
      v8_update_headers: yes
  build-and-test-macos:
    uses: ./.github/workflows/MACOS_REUSABLE.yml
    with:
      v8_version: main
      v8_update_headers: yes
