name: Platform builds

on:
    workflow_dispatch:

    push:
        paths-ignore:
            - '.circleci/**'
            - 'docs/**'
        branches:
            - main

    pull_request:

jobs:

    jammy-x86:
        uses: ./.github/workflows/REUSABLE_DOCKER_BUILDER.yml
        with:
            os_version: 22.04
            dockerfile: dockerbuilds/Dockerfile.jammy