name: Pull Request

on:
    pull_request:

jobs:

    jammy-x86:
        uses: ./.github/workflows/REUSABLE_DOCKER_BUILDER.yml
        with:
            os_version: 22.04
            os_family: ubuntu
            dockerfile: dockerbuilds/dockerfile.debian.tmpl
        secrets:
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY }}
