name: Make a release

on:

  workflow_dispatch:
    inputs:
      milestone:
        description: 'Milestone to release'
        required: true

jobs:

  release:
    runs-on: ubuntu-latest
    steps:
      - name: Setup s3cmd action
        uses: s3-actions/s3cmd@v1.2.0
        with:
          provider: aws
          region: us-east-2
          access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: get files from s3
        run: |
          mkdir s3uploads/
          s3cmd get s3://redismodules/redisgears/snapshots/redisgears2*${{ inputs.milestone }}* s3uploads/
          ls s3uploads

      - name: rename
        shell: bash
        working-directory: s3uploads
        run: |
          realver=`echo ${{inputs.milestone}} | cut -d '-' -f 1-1`
          for i in `ls`; do
            mv $i ${i/v${{ inputs.milestone }}/${realver}}
          done
          ls

      - name: upload to s3
        working-directory: s3uploads
        run: |
          s3cmd put -P * s3://redismodules/redisgears/
