on:
    workflow_call:
        inputs:
            os_version:
                required: true
                type: string
            os_family:
                required: true
                type: string
            dockerfile:
                required: true
                type: string
            arch:
                required: false
                type: string
                default: x86_64
            v8_version:
                default: 'default'
                required: false
                type: string
            v8_update_headers:
                default: 'no'
                required: false
                type: string
            redis_version:
                default: 7.2-rc1
                required: false
                type: string
        secrets:
            AWS_ACCESS_KEY_ID:
                required: false
            AWS_SECRET_ACCESS_KEY:
                required: false

env:
  CARGO_TERM_COLOR: always

jobs:

  build:
    runs-on: ubuntu-latest
    env:
      V8_VERSION: ${{ inputs.v8_version }}
      V8_UPDATE_HEADERS: ${{ inputs.v8_update_headers }}

    steps:
        - uses: actions/setup-python@v4
          with:
            python-version: '3.9'
        - run: pip install jinja2
        - uses: actions/checkout@v3
        - name: generate docker file
          run: |
            python3 dockerbuilds/generate.py --os_version ${{inputs.os_version}} \
              --platform ${{inputs.arch}} --redis_version ${{inputs.redis_version}} \
              --os_family ${{inputs.os_family}}
              --publish
        - name: install qemu
          if: ${{inputs.arch == 'arm64' }}
          uses: docker/setup-qemu-action@v2

        - name: install buildx
          uses: docker/setup-buildx-action@v2

        - name: build
          id: dockerbuild
          uses: docker/build-push-action@v4
          with:
            push: false
            context: .
            file: dockerbuilds/Dockerfile.generated
            build-args: |
                AWS_ACCESS_KEY: ${{secrets.AWS_ACCESS_KEY_ID}}
                AWS_SECRET_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
                v8_version: ${{inputs.v8_version}}
                v8_update_headers: ${{inputs.v8_update_headers}}