name: Ubuntu Focal

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3
    - name: install rltest
      run: pip install RLTest
    - name: install redis
      run: git clone https://github.com/redis/redis; cd redis; git checkout 7.0.3; make install
    - name: format
      run: cargo fmt -- --check
    - name: Build debug
      run: cargo build --verbose
    - name: Build release
      run: cargo build --release --verbose
    - name: Tests
      run: cd pytests;./run_tests.sh
    - name: install ramp packer
      run: pip install git+https://github.com/RedisLabsModules/RAMP.git@master
    - name: Pack
      run: target/release/packer
    - name: Setup s3cmd action
      if: ${{ github.ref_name == 'master' && github.ref_type == 'branch' }}
      uses: s3-actions/s3cmd@v1.2.0
      with:
        provider: aws
        region: us-east-2
        access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
        secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    - name: Upload artifacts
      if: ${{ github.ref_name == 'master' && github.ref_type == 'branch' }}
      run: |
        s3cmd put -P target/release/redisgears2-release.linux-ubuntu.20.04-x86_64.master.zip s3://redismodules/redisgears/snapshots/
